### ISSUE TITLE
Java10 : VAR notation

### ISSUE THREAD

**Issue by tanerdiler** [JUGIstanbul/java9-N#10]
- [ ] Örnekler hazırlanmalı
- [ ] Lambda içerisindeki kullanımları
- [ ] Method reference kullanımları
- [ ] Diğer kısıtlamalar neler

**Comment by tanerdiler** [comment]
@hakdogan package ismini org.jugistanbul.var olarak değiştirebilri miyiz? localvti pek anlaşılmıyor.

**Comment by hakdogan** [comment]
> @hakdogan package ismini org.jugistanbul.var olarak değiştirebilri miyiz? localvti pek anlaşılmıyor.

Tabi, güncellerim. 

Lamda, method reference bunlar açık hedef istedikleri için var ile kullanılamıyor. Koda belki yorum satırı olarak gömülebilir, şu anki boş Diamond örneği gibi...

**Comment by tanerdiler** [comment]
uygundur hocam, bir de okunabilirliliği artırmak anlamında bir örnek de gösterebilriiz. Çünkü senior ve junior developerlar intellij'nin naming suggestionlarını kullanıyolar bi de business'dan dolayı *service *repository değişken isimleri de aynı oluyor. Roman gibi kod oluyor. 

Örnek 

```
AdditionalListingRightService additionalListingRightService = new AdditionalListingRightService();
List<AdditionalListingRightEntity> additionalListingRightList = additionalListingRightService.getAdditionalListingRights();
AdditionatlListingRightResponse response = additionalListingRightService.findWithMaxCredit(additionalListingRightList);
return response;
```
AdditionatlListingRight* şu an iş yerinde üzerinde uğraştığım iş. Maalesef böyle kodlarımız var Intellij'den dolayı. Mecburen AdditionatlListingRight(Response/Service/Repository/Entity) isimlendirmeleri de yapmak zorunda kalıyosun.

VAR hiç olmadı değişken tipini belirtmede karakter sayısını azaltacaktır.
