### ISSUE TITLE
Okunması gereken dokümanlar

### ISSUE THREAD

**Issue by tanerdiler** [JUGIstanbul/java9-N#7]
https://www.yegor256.com/2017/10/03/java9.html
https://vividcode.io/5-things-made-easier-in-java-9/
https://alidg.me/blog/2016/12/30/least-significant-bits-of-java-9

Herbirince çok güzel özellikler anlatılmış:
2. linkte
  - Resource Reference kullanımında kolaylık
  - Optional.stream() new method

    final long count = Stream.of(
      Optional.of(1),
      Optional.empty(),
      Optional.of(2)
    ).flatMap(Optional::stream)
    .count();
  assertEquals(2, count);

 - private interface methods
3. linkte
- Reactive Programming alt yapısı:
   - Publisher & Subscriber & Flow
- CompletableFuture'a timeout function'lar gelmiş
- gün gün artışı stream yapıyor.
birthday
      .datesUntil(LocalDate.now())
       .map....

**Comment by hakdogan** [comment]
Paylaşım için teşekkürler @tanerdiler
